"use client";
import { useMemo, useState } from "react";
import questions from "../public/questions.json";
import { Download, Search, Sparkles, Loader2, MessageSquare } from "lucide-react";

type Q = {sl_no:number|string;question:string;company:string;role:string;domain:string};
type Style = "interviewee"|"normal"|"structured";
const qs=questions as Q[];
const normalize=(s:string)=>s.trim().toLowerCase();
const unique=(xs:string[])=>Array.from(new Set(xs.filter(Boolean))).sort((a,b)=>a.localeCompare(b));

export default function InterviewApp(){
  const companies=useMemo(()=>unique(qs.map(q=>q.company)),[]);
  const [company,setCompany]=useState("");
  const [domain,setDomain]=useState("All domains");
  const [search,setSearch]=useState("");
  const [style,setStyle]=useState<Style>("interviewee");
  const [selected,setSelected]=useState<Q|null>(null);
  const [answers,setAnswers]=useState<Record<string,string>>({});
  const [loading,setLoading]=useState(false);
  const [exporting,setExporting]=useState(false);
  const domains=useMemo(()=>unique(qs.filter(q=>!company||q.company===company).map(q=>q.domain)),[company]);
  const filtered=useMemo(()=>{const term=normalize(search);return qs.filter(q=>(!company||q.company===company)&&(domain==="All domains"||q.domain===domain)&&(!term||normalize(q.question).includes(term)||normalize(q.domain).includes(term)));},[company,domain,search]);
  async function generate(q:Q){setSelected(q);setLoading(true);try{const r=await fetch("/api/answer",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({question:q.question,company:q.company,role:q.role,domain:q.domain,style})});const data=await r.json();if(!r.ok)throw new Error(data.error||"Failed");setAnswers(a=>({...a,[String(q.sl_no)]:data.answer}));}catch(e:any){alert(e.message)}finally{setLoading(false)}}
  async function exportPDF(){if(!company){alert("Select a company first.");return}const companyQs=qs.filter(q=>q.company===company);if(!companyQs.length)return;setExporting(true);try{const newAnswers={...answers};for(const q of companyQs.filter(q=>!newAnswers[String(q.sl_no)])){const r=await fetch("/api/answer",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({question:q.question,company:q.company,role:q.role,domain:q.domain,style})});const d=await r.json();if(!r.ok)throw new Error(d.error||"Failed");newAnswers[String(q.sl_no)]=d.answer}setAnswers(newAnswers);const rows=companyQs.map((q,i)=>`<section class="qa"><div class="q">Q${i+1}. ${escapeHtml(q.question)}</div><div class="meta">${escapeHtml(q.domain)}${q.role?` · ${escapeHtml(q.role)}`:""}</div><div class="a">${nl2br(escapeHtml(newAnswers[String(q.sl_no)]||""))}</div></section>`).join("");const w=window.open("","_blank");if(!w)throw new Error("Popup blocked. Allow popups and try again.");w.document.write(`<!doctype html><html><head><title>${escapeHtml(company)} Interview Answers</title><style>@page{margin:18mm}body{font-family:Arial,sans-serif;color:#14213d;line-height:1.55}h1{font-size:28px;margin-bottom:4px}.subtitle{color:#667085;margin-bottom:24px}.qa{break-inside:avoid;margin:0 0 24px;padding-bottom:18px;border-bottom:1px solid #e5e7eb}.q{font-size:16px;font-weight:700}.meta{font-size:12px;color:#64748b;margin:6px 0 10px}.a{font-size:13px}</style></head><body><h1>${escapeHtml(company)} — Interview Answer Pack</h1><div class="subtitle">${companyQs.length} questions · Style: ${escapeHtml(style)}</div>${rows}<script>window.onload=()=>window.print()</script></body></html>`);w.document.close()}catch(e:any){alert(e.message)}finally{setExporting(false)}}
  return <main className="shell"><header className="topbar"><div><div className="eyebrow"><Sparkles size={15}/> AI INTERVIEW PREP</div><h1>Company Question Lab</h1><p>Filter real interview questions, generate answers, and build a print-ready company pack.</p></div><button className="export" onClick={exportPDF} disabled={exporting||!company}>{exporting?<Loader2 className="spin" size={17}/>:<Download size={17}/>} Export company PDF</button></header><section className="filters"><label>Company<select value={company} onChange={e=>{setCompany(e.target.value);setDomain("All domains");setSelected(null)}}><option value="">All companies</option>{companies.map(c=><option key={c}>{c}</option>)}</select></label><label>Domain<select value={domain} onChange={e=>setDomain(e.target.value)}><option>All domains</option>{domains.map(d=><option key={d}>{d}</option>)}</select></label><label className="search">Search questions<div className="searchbox"><Search size={17}/><input placeholder="e.g. OOP, AWS, SQL..." value={search} onChange={e=>setSearch(e.target.value)}/></div></label><label>Answer style<select value={style} onChange={e=>setStyle(e.target.value as Style)}><option value="interviewee">Interviewee</option><option value="normal">Normal</option><option value="structured">Specific format</option></select></label></section><div className="stats"><span><b>{filtered.length}</b> questions shown</span>{company&&<span className="pill">{company}</span>}</div><section className="workspace"><aside className="list">{filtered.slice(0,250).map((q,i)=><button className={`qcard ${selected?.sl_no===q.sl_no?"active":""}`} onClick={()=>generate(q)} key={`${q.sl_no}-${i}`}><div className="qnum">#{q.sl_no}</div><div className="qtext">{q.question}</div><div className="qmeta">{q.domain}{q.role?` · ${q.role}`:""}{answers[String(q.sl_no)]?<span className="done">Answered</span>:null}</div></button>)}{filtered.length>250&&<div className="more">Showing first 250 matches. Narrow the filters to continue.</div>}</aside><article className="chat"><div className="chathead"><div><div className="chatlabel"><MessageSquare size={16}/> ANSWER STUDIO</div><h2>{selected?"Question answer":"Select a question"}</h2></div><div className="stylepill">{style}</div></div>{!selected?<div className="empty"><Sparkles size={32}/><h3>Choose any question</h3><p>Answers are generated with the selected style and can be included in the company export.</p></div>:<div className="answer"><div className="bubble question"><span>QUESTION</span>{selected.question}</div><div className="bubble response"><span>ANSWER</span>{loading?<div className="typing"><Loader2 className="spin" size={18}/> Drafting answer…</div>:<div className="prose">{answers[String(selected.sl_no)]}</div>}</div></div>}</article></section></main>
}
function escapeHtml(s:string){return s.replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#39;"} as any)[m])}
function nl2br(s:string){return s.replace(/\n/g,"<br/>")}
